### ISSUE TITLE
F-droid

### ISSUE THREAD

**Issue by roshavagarga** [igorescodro/alkaa#247]
Hello, have you considered submitting your app to the main F-droid repository?

**Comment by igorescodro** [comment]
Hello, @roshavagarga!

Alkaa does use some Google Play libraries in order to enable the Dynamic Feature Module.
If this is not an issue for third-party app repositories, I do not oppose to the inclusion of Alkaa there.

Please, let me know your thoughts about it.

**Comment by roshavagarga** [comment]
As far as I know, and I am not a dev, just an enthusiast, for inclusion in the F-Droid main repository, the app needs to use open source modules - anything closed-source or blob-like needs to be switched out in a custom flavor of the app. Stuff like Firebase can be replaced with ACRA, for instance, so depending on what libraries you're using, if you give me a list I can do some digging and present alternatives.

**Comment by igorescodro** [comment]
Hello!
Thanks a lot for the interest in publishing in other app stores.
Although this is not on my backlog at the moment, Alkaa is open-source and all the [unsigned releases of the APK are available at the release notes](https://github.com/igorescodro/alkaa/releases/tag/v2.1.2).

Feel free to grab them and try to publish in other stores, and even recompile the app with some needed changes to better fit the F-Droid or izzyondroid needs.

Thanks!
