### ISSUE TITLE
Add Third Party Libraries License

### ISSUE THREAD

**Issue by igorescodro** [igorescodro/alkaa#69]
Create a screen to show all the third party libraries used in the project (OSS).

**Comment by 2tanayk** [comment]
May I work on this issue?

**Comment by 2tanayk** [comment]
> May I work on this issue?

would be really great if I get to know some more details about this😀

**Comment by igorescodro** [comment]
Hello, @2tanayk 

First of all, thanks a lot of your interest in make Alkaa a better app!
Unfortunately, the project is not open for external PRs at the moment. Specially now that version 1.0 is deprecated in favor of a new one using Jetpack Compose.
When the version 2.0 is more stable and a roadmap is defined for it, I'll be glad to receive your help.

Happy holidays!
